### ISSUE TITLE
seperate admin subdomain or admin folder to seperate it from the front end of the website

### ISSUE THREAD

**Issue by govindbaker** [themeselection/sneat-bootstrap-html-laravel-admin-template-free#4]
### What problem does this feature solve?

Often a website has a front end open to the public and an admin system on a sub domain e.g. admin.domain.com or under a folder e.g. domain.com/admin and the front end of the site is just domain.com.

### What does the proposed solution look like?

allows controllers/views/etc to be separated from the rest of the application

**Comment by monab** [comment]
Hi @govindbaker,

Thanks for getting in touch with us!!
You can customize the way you want but customizations and integrations are not part of the support.

Regards~
