### ISSUE TITLE
Performance for yarn watch

### ISSUE THREAD

**Issue by Arijus** [themeselection/sneat-bootstrap-html-laravel-admin-template-free#8]
### Steps to reproduce

-

### What is expected?

-

### What is actually happening?

Using yarn watch for premium template after changing lets say some variable in .scss it takes to compile admin area like 3 mins.. It should be like this? I even have split admin and front compilation to work faster, but cant handle admin area..

**Comment by smitbhalodiya** [comment]
Hi @Arijus,

Thank you for reaching out about the issue you're experiencing with SCSS compilation times.

Currently, your SCSS compilation is taking longer than expected. It seems that this issue might be related to your **webpack** configuration.
In our Pro version, we have switched from **webpack** to **Vite**. Vite offers faster compilation compared to webpack, which can help resolve this issue.
Additionally, our Pro version includes many applications and pages built with Vite that you can explore in our demo. https://demos.themeselection.com/sneat-bootstrap-html-laravel-admin-template/demo-1/
Upgrading to the Pro version could provide you with a better experience.

Please let us know if you need any further assistance.
